In [1]:
from xgboost import plot_importance
from xgboost import XGBClassifier
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from statsmodels.api import Logit
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

from sklearn.tree import export_graphviz
import graphviz
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import f1_score, roc_curve, auc
from sklearn.svm import SVC
from sklearn.metrics import f1_score, roc_curve, auc,roc_auc_score
from sklearn.neighbors import KNeighborsClassifier

import scipy.stats
from scipy import stats
%matplotlib inline
matplotlib.rc('font',family = 'Malgun Gothic')

In [2]:
# 전처리
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler

# 머신러닝 알고리즘
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier

# 모델 튜닝 및 평가
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_predict
from sklearn import model_selection
import statsmodels.api as sm


In [3]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [4]:
import warnings
warnings.filterwarnings(action='ignore')

In [5]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler

In [6]:
df_raw = pd.read_csv("Dataset_all.csv")
df_raw.drop('Unnamed: 0',axis=1,inplace=True)

In [7]:
# 더미 변수화
df_raw[['Ox_Chamber']]=df_raw[['Ox_Chamber']].astype(str)
df_raw[['photo_soft_Chamber']]=df_raw[['photo_soft_Chamber']].astype(str)
df_raw[['lithography_Chamber']]=df_raw[['lithography_Chamber']].astype(str)
df_raw[['Etching_Chamber']]=df_raw[['Etching_Chamber']].astype(str)
df_raw[['Chamber_Num']]=df_raw[['Chamber_Num']].astype(str)
df_raw[['Wavelength']]=df_raw[['Wavelength']].astype(str)

# wet, dry 구분
# df_raw.loc[df_raw['type']=='dry','type']=0
# df_raw.loc[df_raw['type']=='wet','type']=1

# Vapor / H2O, O2 구분
df_raw.loc[df_raw['Vapor']=='H2O','Vapor']=0
df_raw.loc[df_raw['Vapor']=='O2','Vapor']=1

# Wavelength 365, 405, 436
df_raw.loc[df_raw['Wavelength']=='365','Wavelength']=0
df_raw.loc[df_raw['Wavelength']=='405','Wavelength']=1
df_raw.loc[df_raw['Wavelength']=='436','Wavelength']=2


# 필요 없는 변수 material, current, lamp, chamber, type제거
# df_list_before=['Temp_OXid', 'Vapor', 'ppm','Pressure', 'Oxid_time', 'thickness',
#         'resist_target', 'N2_HMDS', 'pressure_HMDS', 'temp_HMDS','temp_HMDS_bake', 'time_HMDS_bake', 'spin1', 'spin2', 'spin3','photoresist_bake', 'temp_softbake', 'time_softbake',
#         'Line_CD','Wavelength', 'Resolution', 'Energy_Exposure',
#         'Thin F4','Thin F2','Thin F3','Thin F1', 'Temp_Etching','Source_Power', 'Selectivity',
#         'Flux60s', 'Flux90s', 'Flux160s', 'Flux480s','Flux840s', 'input_Energy', 'Temp_implantation','Furance_Temp', 'RTA_Temp']

# df_dummy=pd.get_dummies(df_raw[df_list_before])

# # 불량판단 기준 달라질 것. 이 파라미터에 따른 성능 생각할 필요
# Y_wet.loc[Y_wet.Target<183]=0
# Y_wet.loc[Y_wet.Target>=183]=1
# Y_dry.loc[Y_dry.Target<183]=0
# Y_dry.loc[Y_dry.Target>=183]=1
# len(X),len(Y)
# df_train_x,df_test_x,df_train_y,df_test_y = train_test_split(X,Y,test_size = 0.3,random_state = 1234)

In [8]:
df_raw.loc[df_raw.Target>=183,'Quality']=1
df_raw.loc[df_raw.Target<183,'Quality']=0

In [9]:
# 제일 좋은 것 같은데
imp_features=['Temp_OXid', 'Thin F4', 'Thin F2', 'Flux480s', 'Source_Power',
        'thickness', 'Pressure', 'Energy_Exposure',
       'photoresist_bake', 'spin2', 'temp_HMDS_bake','Temp_implantation']
df_dummy=pd.get_dummies(df_raw[imp_features])
# ppm 제거

In [10]:
df_train_x,df_test_x,df_train_y,df_test_y = train_test_split(df_dummy,df_raw['Quality'],test_size = 0.3,random_state = 1234)

In [11]:
df_test_x

Temp_OXid  Thin F4  Thin F2      Flux480s  Source_Power  thickness  \
326  1267.846723    224.0   3645.0  2.982513e+17        50.431    703.950   
771   871.477974    174.0   3635.0  2.993495e+17        51.358    709.835   
288  1159.860168    387.0   3658.0  2.982403e+17        50.787    706.277   
230  1282.303070    175.0   3646.0  2.993413e+17        50.185    716.564   
362  1280.077304    177.0   3634.0  3.014882e+17        50.792    709.301   
..           ...      ...      ...           ...           ...        ...   
137  1270.342348    361.0   3661.0  3.006096e+17        51.138    724.096   
9    1269.092800    178.0   3648.0  3.002527e+17        50.839    721.528   
77    871.800986    326.0   3653.0  3.006004e+17        51.904    715.604   
475   870.794989    183.0   3615.0  2.987389e+17        50.559    690.969   
523   872.619189    213.0   3641.0  3.000910e+17        51.247    713.575   

     Pressure  Energy_Exposure  photoresist_bake     spin2  temp_HMDS_bake  \
326     0.217          106.328             5.063  4049.123         202.456   
771     0.213          108.407             5.065  4074.581         203.729   
288     0.202          111.001             5.004  4036.214         205.521   
230     0.215          105.132             5.021  4017.361         200.868   
362     0.216          106.102             5.103  4103.032         205.152   
..        ...              ...               ...       ...             ...   
137     0.223          107.722             4.934  3944.064         197.203   
9       0.217          107.212             5.016  3998.147         199.907   
77      0.219          108.335             4.986  3987.046         199.352   
475     0.192          107.851             5.110  4100.279         205.014   
523     0.217          107.943             5.032  4026.554         201.328   

     Temp_implantation  
326            101.078  
771            103.396  
288            100.362  
230            100.463  
362            101.980  
..                 ...  
137            102.845  
9              102.099  
77             104.759  
475            101.397  
523            103.119  

[249 rows x 12 columns]

In [12]:
df_test_x_1 = pd.DataFrame()

In [13]:
df_test_x_1 = df_test_x.copy()

In [14]:
range_1 = [] #Temp_Oxid
range_2 = [] #Pressure
range_3 = [] #temp_HMDS_bake
range_4 = [] #photoresist_bake
range_5 = [] #spin2
range_6 = [] #Temp_implantation

In [15]:
for i in range(1, 250):
    range_1.append(random.uniform(1282.139,1310.709))
    range_2.append(random.uniform(0.180,0.193))
    range_3.append(random.uniform(207.765,209.521))
    range_4.append(random.uniform(1282.139,1310.709))
    range_5.append(random.uniform(4105.862,4208.676))
    range_6.append(random.uniform(97.744,100.22))

In [16]:
pd.set_option('display.max_row', None)
pd.set_option('display.max_columns', None)

In [17]:
df_test_x_1[['Temp_OXid','Pressure','temp_HMDS_bake','photoresist_bake','spin2','Temp_implantation']]

Temp_OXid  Pressure  temp_HMDS_bake  photoresist_bake     spin2  \
326  1267.846723     0.217         202.456             5.063  4049.123   
771   871.477974     0.213         203.729             5.065  4074.581   
288  1159.860168     0.202         205.521             5.004  4036.214   
230  1282.303070     0.215         200.868             5.021  4017.361   
362  1280.077304     0.216         205.152             5.103  4103.032   
72   1103.547945     0.210         202.072             5.107  3999.030   
415  1287.435437     0.203         197.046             5.067  4010.001   
301  1130.769716     0.196         204.080             4.964  4071.649   
746  1274.667489     0.224         196.262             4.904  3925.230   
406  1054.787096     0.210         200.051             5.076  4052.404   
534   913.970809     0.209         198.866             4.957  3988.812   
128   989.411946     0.204         204.544             5.055  4124.099   
825  1275.182502     0.214         204.429             5.114  4088.587   
647  1000.063674     0.203         200.039             4.937  4029.120   
422   979.536060     0.214         201.138             5.107  4042.392   
124  1120.908253     0.215         202.192             5.050  4049.729   
143  1107.490734     0.201         199.470             4.871  4040.679   
511  1033.025944     0.216         201.470             5.082  3914.265   
515   994.591479     0.207         200.635             5.012  3939.275   
445  1189.072862     0.203         195.162             5.041  4001.948   
616   871.465160     0.214         202.059             5.062  4041.184   
456  1151.870204     0.204         200.693             5.083  3949.569   
827  1107.041866     0.212         199.032             4.915  4086.597   
329  1162.223804     0.221         197.129             4.920  4058.777   
373  1013.523745     0.217         204.107             4.881  4152.677   
240   871.057090     0.214         203.303             5.079  4066.052   
594   872.300185     0.210         204.893             5.124  4097.866   
163   872.369546     0.217         200.125             5.010  4002.491   
146   871.479590     0.220         200.323             4.982  4006.461   
89   1266.660904     0.213         200.716             5.019  4014.329   
786  1280.587718     0.219         199.697             4.995  3993.937   
60   1062.467808     0.217         202.139             5.151  3981.691   
709  1096.383491     0.201         204.133             5.004  3992.433   
535  1109.556941     0.211         199.632             5.030  3999.733   
355  1062.490887     0.211         201.257             5.028  3943.713   
483  1011.298567     0.195         199.004             4.867  4063.095   
328  1013.429731     0.199         204.410             4.997  4052.219   
156  1114.322932     0.209         201.670             5.121  4037.619   
776   872.319494     0.218         200.699             5.013  4013.975   
214   872.314548     0.208         204.560             5.135  4091.194   
78   1240.289547     0.204         199.620             4.920  4045.078   
320   901.276944     0.222         198.578             4.925  3998.943   
207   862.011276     0.195         202.275             5.000  4116.758   
169  1058.509868     0.206         205.939             4.933  4022.109   
451  1091.757943     0.188         203.109             5.037  4015.297   
166   871.667823     0.213         203.145             5.085  4062.910   
40   1181.260480     0.216         198.470             5.013  4012.451   
171  1236.932859     0.203         201.173             4.928  4073.840   
245  1151.560926     0.206         201.381             5.043  4017.526   
495   872.867933     0.213         202.240             5.065  4044.792   
356   874.102074     0.227         195.579             4.899  3911.573   
590   872.381985     0.216         204.702             5.107  4094.047   
810  1268.921933     0.216         203.281             4.969  4011.123   
692  1124.1

In [18]:
range1 = pd.DataFrame()
range2 = pd.DataFrame()
range3 = pd.DataFrame()
range4 = pd.DataFrame()
range5 = pd.DataFrame()
range6 = pd.DataFrame()

In [19]:
range1 = range_1
range2 = range_2
range3 = range_3
range4 = range_4
range5 = range_5
range6 = range_6

In [20]:
df_test_x_1.columns

Index(['Temp_OXid', 'Thin F4', 'Thin F2', 'Flux480s', 'Source_Power',
       'thickness', 'Pressure', 'Energy_Exposure', 'photoresist_bake', 'spin2',
       'temp_HMDS_bake', 'Temp_implantation'],
      dtype='object')

In [21]:
df_test_x_1['Temp_OXid'] = range1
df_test_x_1['Pressure'] = range2
df_test_x_1['temp_HMDS_bake'] = range3
df_test_x_1['photoresist_bake'] = range4
df_test_x_1['spin2'] = range5
df_test_x_1['Temp_implantation'] = range5

In [22]:
df_test_x_1[['Temp_OXid','Pressure','temp_HMDS_bake','photoresist_bake','spin2','Temp_implantation']]

Temp_OXid  Pressure  temp_HMDS_bake  photoresist_bake        spin2  \
326  1298.673995  0.183527      208.762489       1293.306623  4187.906411   
771  1289.691013  0.181625      209.034325       1301.510718  4137.469703   
288  1288.544431  0.182742      209.034238       1294.471336  4149.686418   
230  1304.719067  0.188451      208.802718       1284.053884  4188.528656   
362  1303.477061  0.189863      208.634411       1286.794699  4127.819516   
72   1309.905931  0.188617      208.053640       1309.740764  4147.738602   
415  1284.436680  0.187513      208.442452       1290.377984  4201.395069   
301  1308.550589  0.188481      207.952944       1289.401714  4160.353739   
746  1293.005284  0.187123      209.439051       1299.991940  4107.502811   
406  1284.214040  0.185487      209.441704       1299.151188  4202.689269   
534  1307.980268  0.186974      208.135369       1307.219247  4166.490833   
128  1291.934178  0.182082      207.776563       1310.231027  4124.087596   
825  1284.250616  0.184611      208.441489       1304.481893  4139.779375   
647  1300.836693  0.182621      208.140190       1289.779523  4157.051780   
422  1283.638480  0.180934      209.250028       1301.732236  4125.792968   
124  1307.893250  0.180431      207.799126       1283.304776  4190.631249   
143  1297.234039  0.181925      209.179333       1290.944499  4206.074254   
511  1292.803341  0.192864      208.464481       1285.685670  4207.102627   
515  1301.122471  0.192817      207.887207       1291.934222  4156.347545   
445  1289.905229  0.191603      208.826786       1289.303707  4121.845895   
616  1289.066298  0.191421      209.441543       1290.273612  4199.241020   
456  1299.354893  0.184633      209.226961       1288.698899  4179.269385   
827  1288.722912  0.182274      209.407053       1308.714683  4167.266441   
329  1299.932152  0.192909      207.853396       1302.334803  4115.587728   
373  1285.565205  0.181959      208.257673       1296.691137  4164.892189   
240  1309.979288  0.188713      209.283735       1291.493789  4128.683208   
594  1292.081157  0.184844      208.063519       1291.849602  4194.442275   
163  1293.548042  0.186013      207.844458       1300.472945  4169.990245   
146  1308.743798  0.187560      208.329678       1283.218901  4107.911971   
89   1303.769522  0.183432      208.827154       1288.366479  4160.588065   
786  1299.205096  0.181120      208.394871       1286.728097  4184.560634   
60   1287.903487  0.180279      208.340688       1287.691678  4121.772660   
709  1294.665856  0.190083      209.273406       1305.587125  4207.596405   
535  1303.242109  0.189151      209.058579       1301.095150  4127.306144   
355  1306.828488  0.191724      207.994476       1310.317200  4106.335658   
483  1295.484210  0.189738      207.769635       1301.154559  4207.498870   
328  1297.162478  0.189907      209.459138       1298.827851  4149.950769   
156  1306.377417  0.181484      208.597746       1302.404478  4198.355229   
776  1292.819666  0.185974      208.852364       1305.821535  4118.960555   
214  1283.282836  0.188176      209.387745       1285.014270  4175.091659   
78   1286.885988  0.186537      209.317235       1295.466051  4173.355062   
320  1300.571070  0.186732      207.833370       1300.170545  4128.333465   
207  1298.360899  0.187483      208.365108       1307.958978  4132.338855   
169  1298.256530  0.188076      207.864912       1310.328858  4180.060340   
451  1285.562482  0.188768      208.942033       1302.966440  4134.635775   
166  1304.903720  0.190758      208.968239       1294.022755  4169.597055   
40   1292.632117  0.187361      209.165626       1297.833268  4114.058206   
171  1289.497294  0.189061      207.859548       1303.289174  4183.178650   
245  1305.229432  0.185471      209.083114       1295.171664  4202.504792   
495  1310.589107  0.190370      209.412507       1290.061459  4182.713856   
356  1306.972589  0.184351      208.542672       1287.033462  4178.809290   
590

In [23]:
df_test_x_1

Temp_OXid  Thin F4  Thin F2      Flux480s  Source_Power  thickness  \
326  1298.673995    224.0   3645.0  2.982513e+17        50.431    703.950   
771  1289.691013    174.0   3635.0  2.993495e+17        51.358    709.835   
288  1288.544431    387.0   3658.0  2.982403e+17        50.787    706.277   
230  1304.719067    175.0   3646.0  2.993413e+17        50.185    716.564   
362  1303.477061    177.0   3634.0  3.014882e+17        50.792    709.301   
72   1309.905931    456.0   3638.0  2.981188e+17        51.156    716.988   
415  1284.436680    304.0   3625.0  2.971368e+17        51.062    714.203   
301  1308.550589    448.0   3654.0  2.985401e+17        51.969    726.396   
746  1293.005284    169.0   3668.0  2.999457e+17        51.236    726.633   
406  1284.214040    366.0   3654.0  3.013019e+17        50.583    697.237   
534  1307.980268    353.0   3649.0  3.007564e+17        51.616    711.451   
128  1291.934178    419.0   3667.0  3.005576e+17        51.996    716.975   
825  1284.250616    177.0   3655.0  3.009325e+17        50.601    715.498   
647  1300.836693    660.0   3679.0  3.011953e+17        50.653    715.592   
422  1283.638480    489.0   3657.0  3.007530e+17        51.530    711.227   
124  1307.893250    219.0   3637.0  3.018136e+17        50.787    707.911   
143  1297.234039    443.0   3625.0  3.017596e+17        51.661    722.297   
511  1292.803341    325.0   3656.0  3.001714e+17        50.901    699.237   
515  1301.122471    263.0   3660.0  2.999889e+17        49.794    711.111   
445  1289.905229    308.0   3675.0  2.989406e+17        51.573    713.775   
616  1289.066298    217.0   3641.0  3.014131e+17        51.277    710.727   
456  1299.354893    348.0   3649.0  3.012983e+17        50.224    703.333   
827  1288.722912    261.0   3661.0  2.983640e+17        49.957    719.257   
329  1299.932152    405.0   3630.0  3.003981e+17        50.321    699.764   
373  1285.565205    348.0   3639.0  3.003610e+17        50.691    715.371   
240  1309.979288    218.0   3635.0  3.019191e+17        51.750    710.547   
594  1292.081157    276.0   3635.0  3.008417e+17        52.072    707.023   
163  1293.548042    200.0   3635.0  3.003910e+17        51.626    713.465   
146  1308.743798    325.0   3657.0  2.990722e+17        52.030    716.480   
89   1303.769522    212.0   3630.0  3.002508e+17        49.922    699.176   
786  1299.205096    261.0   3647.0  2.999631e+17        50.401    716.920   
60   1287.903487    411.0   3644.0  2.994231e+17        51.610    705.471   
709  1294.665856    544.0   3663.0  3.000866e+17        51.426    705.135   
535  1303.242109    498.0   3632.0  3.034721e+17        50.718    707.715   
355  1306.828488    431.0   3654.0  2.977746e+17        50.522    696.504   
483  1295.484210    233.0   3677.0  3.009846e+17        49.761    703.756   
328  1297.162478    362.0   3683.0  3.025094e+17        50.902    721.595   
156  1306.377417    287.0   3671.0  2.987405e+17        50.574    717.471   
776  1292.819666    177.0   3641.0  3.006929e+17        51.471    714.770   
214  1283.282836    225.0   3638.0  2.993609e+17        52.299    704.746   
78   1286.885988    288.0   3669.0  3.012355e+17        52.479    707.180   
320  1300.571070    210.0   3653.0  3.006359e+17        49.600    708.489   
207  1298.360899    337.0   3656.0  2.987506e+17        51.688    703.906   
169  1298.256530    301.0   3681.0  3.010948e+17        51.312    700.946   
451  1285.562482    330.0   3659.0  3.025050e+17        50.324    708.825   
166  1304.903720    193.0   3634.0  2.997104e+17        51.720    710.084   
40   1292.632117    169.0   3664.0  3.023853e+17        51.628    712.668   
171  1289.497294     99.0   3653.0  2.989704e+17        50.909    708.257   
245  1305.229432    195.0   3651.0  3.010757e+17        50.623    708.267   
495  1310.589107    268.0   3642.0  3.017982e+17        51.681    710.068   
356  1306.972589    482.0   3679.0  3.004170e+17        51.358    723.381   
590

In [24]:
df_test_x

Temp_OXid  Thin F4  Thin F2      Flux480s  Source_Power  thickness  \
326  1267.846723    224.0   3645.0  2.982513e+17        50.431    703.950   
771   871.477974    174.0   3635.0  2.993495e+17        51.358    709.835   
288  1159.860168    387.0   3658.0  2.982403e+17        50.787    706.277   
230  1282.303070    175.0   3646.0  2.993413e+17        50.185    716.564   
362  1280.077304    177.0   3634.0  3.014882e+17        50.792    709.301   
72   1103.547945    456.0   3638.0  2.981188e+17        51.156    716.988   
415  1287.435437    304.0   3625.0  2.971368e+17        51.062    714.203   
301  1130.769716    448.0   3654.0  2.985401e+17        51.969    726.396   
746  1274.667489    169.0   3668.0  2.999457e+17        51.236    726.633   
406  1054.787096    366.0   3654.0  3.013019e+17        50.583    697.237   
534   913.970809    353.0   3649.0  3.007564e+17        51.616    711.451   
128   989.411946    419.0   3667.0  3.005576e+17        51.996    716.975   
825  1275.182502    177.0   3655.0  3.009325e+17        50.601    715.498   
647  1000.063674    660.0   3679.0  3.011953e+17        50.653    715.592   
422   979.536060    489.0   3657.0  3.007530e+17        51.530    711.227   
124  1120.908253    219.0   3637.0  3.018136e+17        50.787    707.911   
143  1107.490734    443.0   3625.0  3.017596e+17        51.661    722.297   
511  1033.025944    325.0   3656.0  3.001714e+17        50.901    699.237   
515   994.591479    263.0   3660.0  2.999889e+17        49.794    711.111   
445  1189.072862    308.0   3675.0  2.989406e+17        51.573    713.775   
616   871.465160    217.0   3641.0  3.014131e+17        51.277    710.727   
456  1151.870204    348.0   3649.0  3.012983e+17        50.224    703.333   
827  1107.041866    261.0   3661.0  2.983640e+17        49.957    719.257   
329  1162.223804    405.0   3630.0  3.003981e+17        50.321    699.764   
373  1013.523745    348.0   3639.0  3.003610e+17        50.691    715.371   
240   871.057090    218.0   3635.0  3.019191e+17        51.750    710.547   
594   872.300185    276.0   3635.0  3.008417e+17        52.072    707.023   
163   872.369546    200.0   3635.0  3.003910e+17        51.626    713.465   
146   871.479590    325.0   3657.0  2.990722e+17        52.030    716.480   
89   1266.660904    212.0   3630.0  3.002508e+17        49.922    699.176   
786  1280.587718    261.0   3647.0  2.999631e+17        50.401    716.920   
60   1062.467808    411.0   3644.0  2.994231e+17        51.610    705.471   
709  1096.383491    544.0   3663.0  3.000866e+17        51.426    705.135   
535  1109.556941    498.0   3632.0  3.034721e+17        50.718    707.715   
355  1062.490887    431.0   3654.0  2.977746e+17        50.522    696.504   
483  1011.298567    233.0   3677.0  3.009846e+17        49.761    703.756   
328  1013.429731    362.0   3683.0  3.025094e+17        50.902    721.595   
156  1114.322932    287.0   3671.0  2.987405e+17        50.574    717.471   
776   872.319494    177.0   3641.0  3.006929e+17        51.471    714.770   
214   872.314548    225.0   3638.0  2.993609e+17        52.299    704.746   
78   1240.289547    288.0   3669.0  3.012355e+17        52.479    707.180   
320   901.276944    210.0   3653.0  3.006359e+17        49.600    708.489   
207   862.011276    337.0   3656.0  2.987506e+17        51.688    703.906   
169  1058.509868    301.0   3681.0  3.010948e+17        51.312    700.946   
451  1091.757943    330.0   3659.0  3.025050e+17        50.324    708.825   
166   871.667823    193.0   3634.0  2.997104e+17        51.720    710.084   
40   1181.260480    169.0   3664.0  3.023853e+17        51.628    712.668   
171  1236.932859     99.0   3653.0  2.989704e+17        50.909    708.257   
245  1151.560926    195.0   3651.0  3.010757e+17        50.623    708.267   
495   872.867933    268.0   3642.0  3.017982e+17        51.681    710.068   
356   874.102074    482.0   3679.0  3.004170e+17        51.358    723.381   
590

In [25]:
xgb_model = XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, gamma=0, gpu_id=-1,
                               importance_type='gain',
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=5, max_leaves=1, min_child_weight=1,
                               monotone_constraints='()',
                               n_estimators=100, n_jobs=4, num_parallel_tree=1,
                               process_type='default', random_state=1234,
                               reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
                               subsample=0.8, tree_method='exact',
                               validate_parameters=1, verbosity=None)

In [26]:
accuracy_test=[]
precision=[]
recall=[]
F1=[]

## XGB

In [27]:
xgb_model.fit(df_train_x,df_train_y)

[16:22:32] WARNING: ../src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=5,
              max_leaves=1, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=4,
              num_parallel_tree=1, process_type='default', random_state=1234,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=0.8,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [28]:
y_pred = xgb_model.predict_proba(df_test_x)
threshold=0.2
y_pred[:,1][y_pred[:,1]>=threshold]=1
y_pred[:,1][y_pred[:,1]<threshold]=0
# print('Confustion matrix : \n{}'.format(confusion_matrix(df_test_y, y_pred[:,1])))
print('Confustion matrix : \n{}'.format(confusion_matrix(df_test_y, y_pred[:,1])))
print(accuracy_score(df_test_y, y_pred[:,1]))
print(precision_score(df_test_y, y_pred[:,1]))
print(recall_score(df_test_y, y_pred[:,1]))
print(f1_score(df_test_y, y_pred[:,1]))

Confustion matrix : 
[[217   7]
 [ 10  15]]
0.9317269076305221
0.6818181818181818
0.6
0.6382978723404256


In [29]:
y_pred

array([[9.9984688e-01, 0.0000000e+00],
       [9.9976099e-01, 0.0000000e+00],
       [9.9754041e-01, 0.0000000e+00],
       [9.9954146e-01, 0.0000000e+00],
       [9.9859226e-01, 0.0000000e+00],
       [9.9907291e-01, 0.0000000e+00],
       [9.9987739e-01, 0.0000000e+00],
       [9.9361527e-01, 0.0000000e+00],
       [9.9804282e-01, 0.0000000e+00],
       [9.9754858e-01, 0.0000000e+00],
       [9.3854022e-01, 0.0000000e+00],
       [9.9800569e-01, 0.0000000e+00],
       [9.9920934e-01, 0.0000000e+00],
       [6.8588245e-01, 1.0000000e+00],
       [2.7404344e-01, 1.0000000e+00],
       [9.9979955e-01, 0.0000000e+00],
       [9.9729830e-01, 0.0000000e+00],
       [9.9935216e-01, 0.0000000e+00],
       [9.9931329e-01, 0.0000000e+00],
       [9.9865288e-01, 0.0000000e+00],
       [9.9970138e-01, 0.0000000e+00],
       [9.9206686e-01, 0.0000000e+00],
       [9.9930173e-01, 0.0000000e+00],
       [9.9780869e-01, 0.0000000e+00],
       [9.9975544e-01, 0.0000000e+00],
       [9.9899906e-01, 0.

In [30]:
y_pred_f = xgb_model.predict_proba(df_test_x_1)
threshold=0.2
y_pred_f[:,1][y_pred_f[:,1]>=threshold]=1
y_pred_f[:,1][y_pred_f[:,1]<threshold]=0
# print('Confustion matrix : \n{}'.format(confusion_matrix(df_test_y, y_pred[:,1])))
print('Confustion matrix : \n{}'.format(confusion_matrix(df_test_y, y_pred_f[:,1])))
print(accuracy_score(df_test_y, y_pred_f[:,1]))
print(precision_score(df_test_y, y_pred_f[:,1]))
print(recall_score(df_test_y, y_pred_f[:,1]))
print(f1_score(df_test_y, y_pred_f[:,1]))

Confustion matrix : 
[[213  11]
 [ 14  11]]
0.8995983935742972
0.5
0.44
0.46808510638297873


In [31]:
y_pred_f

array([[0.9988066 , 0.        ],
       [0.9994994 , 0.        ],
       [0.8770466 , 0.        ],
       [0.9990762 , 0.        ],
       [0.99749786, 0.        ],
       [0.9876003 , 0.        ],
       [0.9994457 , 0.        ],
       [0.8297751 , 0.        ],
       [0.99949896, 0.        ],
       [0.9684064 , 0.        ],
       [0.9713779 , 0.        ],
       [0.9391872 , 0.        ],
       [0.9975712 , 0.        ],
       [0.3853221 , 1.        ],
       [0.32372713, 1.        ],
       [0.99793816, 0.        ],
       [0.9732553 , 0.        ],
       [0.99510133, 0.        ],
       [0.9966109 , 0.        ],
       [0.99586   , 0.        ],
       [0.99905175, 0.        ],
       [0.9230231 , 0.        ],
       [0.99775535, 0.        ],
       [0.9456934 , 0.        ],
       [0.9939633 , 0.        ],
       [0.9987448 , 0.        ],
       [0.99758977, 0.        ],
       [0.99949074, 0.        ],
       [0.9898816 , 0.        ],
       [0.9981713 , 0.        ],
       [0.

In [32]:
y = y_pred[:,1].astype(int)

In [33]:
y = list(y)
y.count(1)

22

In [34]:
y_ = y_pred_f[:,1].astype(int)

In [35]:

y_ = list(y_)
y_.count(1)

22

In [172]:
accuracy_test.append(accuracy_score(df_test_y, y_pred[:,1]))
precision.append(precision_score(df_test_y, y_pred[:,1]))
recall.append(recall_score(df_test_y, y_pred[:,1]))
F1.append(f1_score(df_test_y, y_pred[:,1]))

## GB

In [173]:
gb_fianl=GradientBoostingClassifier(ccp_alpha=0.0,
                            criterion='friedman_mse', init=None,
                            learning_rate=0.1, loss='deviance',
                            max_depth=3, max_features=None,
                            max_leaf_nodes=None,
                            min_impurity_decrease=0.0,
                            min_impurity_split=None,
                            min_samples_leaf=1,
                            min_samples_split=2,
                            min_weight_fraction_leaf=0.0,
                            n_estimators=100,
                            n_iter_no_change=None,
                            presort='deprecated',
                            random_state=None, subsample=1.0,
                            tol=0.0001, validation_fraction=0.1,
                            verbose=0, warm_start=False)
gb_fianl.fit(df_train_x,df_train_y)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [174]:
y_pred = gb_fianl.predict_proba(df_test_x)
threshold=0.2
y_pred[y_pred[:,1]>=threshold]=1
y_pred[y_pred[:,1]<threshold]=0
print('Confustion matrix : \n{}'.format(confusion_matrix(df_test_y, y_pred[:,1])))
print(accuracy_score(df_test_y, y_pred[:,1]))
print(precision_score(df_test_y, y_pred[:,1]))
print(recall_score(df_test_y, y_pred[:,1]))
print(f1_score(df_test_y, y_pred[:,1]))

Confustion matrix : 
[[212  12]
 [  8  17]]
0.9196787148594378
0.5862068965517241
0.68
0.6296296296296295


In [175]:
accuracy_test.append(accuracy_score(df_test_y, y_pred[:,1]))
precision.append(precision_score(df_test_y, y_pred[:,1]))
recall.append(recall_score(df_test_y, y_pred[:,1]))
F1.append(f1_score(df_test_y, y_pred[:,1]))

## RF

In [176]:
rf_final=RandomForestClassifier(bootstrap=True,
                       ccp_alpha=0.0,
                       class_weight=None,
                       criterion='gini',
                       max_depth=None,
                       max_features='auto',
                       max_leaf_nodes=None,
                       max_samples=None,
                       min_weight_fraction_leaf=0.0,
                       n_estimators=100,
                       n_jobs=None,
                       oob_score=False,
                       random_state=None,
                       verbose=0,
                       warm_start=False)
rf_final.fit(df_train_x,df_train_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [177]:
y_pred = rf_final.predict_proba(df_test_x)
threshold=0.2
y_pred[y_pred[:,1]>=threshold]=1
y_pred[y_pred[:,1]<threshold]=0
print('Confustion matrix : \n{}'.format(confusion_matrix(df_test_y, y_pred[:,1])))
print(accuracy_score(df_test_y, y_pred[:,1]))
print(precision_score(df_test_y, y_pred[:,1]))
print(recall_score(df_test_y, y_pred[:,1]))
print(f1_score(df_test_y, y_pred[:,1]))

Confustion matrix : 
[[202  22]
 [  3  22]]
0.8995983935742972
0.5
0.88
0.6376811594202899


In [178]:
accuracy_test.append(accuracy_score(df_test_y, y_pred[:,1]))
precision.append(precision_score(df_test_y, y_pred[:,1]))
recall.append(recall_score(df_test_y, y_pred[:,1]))
F1.append(f1_score(df_test_y, y_pred[:,1]))

## DT

In [179]:
dt_final=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                        criterion='gini', max_depth=4,
                                        max_features=None, max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=20,
                                        min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        presort='deprecated', random_state=None,
                                        splitter='best')
dt_final.fit(df_train_x,df_train_y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=20, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [180]:
y_pred = dt_final.predict_proba(df_test_x)
threshold=0.2
y_pred[y_pred[:,1]>=threshold]=1
y_pred[y_pred[:,1]<threshold]=0
print('Confustion matrix : \n{}'.format(confusion_matrix(df_test_y, y_pred[:,1])))
print(accuracy_score(df_test_y, y_pred[:,1]))
print(precision_score(df_test_y, y_pred[:,1]))
print(recall_score(df_test_y, y_pred[:,1]))
print(f1_score(df_test_y, y_pred[:,1]))

Confustion matrix : 
[[204  20]
 [  2  23]]
0.9116465863453815
0.5348837209302325
0.92
0.6764705882352942


In [181]:
accuracy_test.append(accuracy_score(df_test_y, y_pred[:,1]))
precision.append(precision_score(df_test_y, y_pred[:,1]))
recall.append(recall_score(df_test_y, y_pred[:,1]))
F1.append(f1_score(df_test_y, y_pred[:,1]))

## SVM

In [182]:
svm_final=SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='scale', kernel='rbf', max_iter=-1,
                     probability=True, random_state=None, shrinking=True,
                     tol=0.001, verbose=False)
svm_final.fit(df_train_x,df_train_y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [183]:
y_pred = svm_final.predict_proba(df_test_x)
threshold=0.2
y_pred[y_pred[:,1]>=threshold]=1
y_pred[y_pred[:,1]<threshold]=0
print('Confustion matrix : \n{}'.format(confusion_matrix(df_test_y, y_pred[:,1])))
print(accuracy_score(df_test_y, y_pred[:,1]))
print(precision_score(df_test_y, y_pred[:,1]))
print(recall_score(df_test_y, y_pred[:,1]))
print(f1_score(df_test_y, y_pred[:,1]))

Confustion matrix : 
[[186  38]
 [ 24   1]]
0.751004016064257
0.02564102564102564
0.04
0.03125


In [184]:
accuracy_test.append(accuracy_score(df_test_y, y_pred[:,1]))
precision.append(precision_score(df_test_y, y_pred[:,1]))
recall.append(recall_score(df_test_y, y_pred[:,1]))
F1.append(f1_score(df_test_y, y_pred[:,1]))

## 로지스틱 회귀

In [185]:
df_raw_logit=df_raw
df_raw_logit.rename(columns = {'Thin F1' : 'Thin_F1','Thin F2' : 'Thin_F2','Thin F3' : 'Thin_F3','Thin F4' : 'Thin_F4'}, inplace = True)
df_train_logit, df_test_logit = train_test_split(df_raw_logit, test_size = 0.3, random_state = 1234)

In [186]:
# from_formula 함수를 이용하여 변수 역할 지정
# 분석 대상 이벤트 = “1”
log_model = Logit.from_formula("""Quality ~ Thin_F4 + Thin_F2 + Thin_F3 + Pressure + Flux90s +
 ppm""", df_train_logit)
# 적합
log_result = log_model.fit()
# 결과 출력
print(log_result.summary())

Optimization terminated successfully.
         Current function value: 0.151028
         Iterations 9
                           Logit Regression Results                           
Dep. Variable:                Quality   No. Observations:                  581
Model:                          Logit   Df Residuals:                      580
Method:                           MLE   Df Model:                            0
Date:                Thu, 18 Mar 2021   Pseudo R-squ.:                  0.5117
Time:                        11:59:10   Log-Likelihood:                -87.747
converged:                       True   LL-Null:                       -179.70
Covariance Type:            nonrobust   LLR p-value:                       nan
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -265.0517     47.530     -5.577      0.000    -358.209    -171.894
Thin_F4        0.0172      0.

In [187]:
y_pred = log_result.predict(df_test_logit)
th = 0.2
# 0과 1의 값을 가진 class로 변환
y_pred_class = (y_pred > th).astype(int)
# 실제 test 데이터의 목표변수와 test 데이터의 예측값 비교
print("Accuracy: {0:.3f}".format(accuracy_score(df_test_logit["Quality"], y_pred_class)))
print("f1: {0:.3f}".format(f1_score(df_test_logit["Quality"], y_pred_class)))
print("recall: {0:.3f}\n".format(recall_score(df_test_logit["Quality"], y_pred_class)))

print("Confusion Matrix: \n{}".format(confusion_matrix(df_test_logit["Quality"], y_pred_class)))

Accuracy: 0.859
f1: 0.507
recall: 0.720

Confusion Matrix: 
[[196  28]
 [  7  18]]


In [188]:
accuracy_test.append(accuracy_score(df_test_logit["Quality"], y_pred_class))
precision.append(precision_score(df_test_logit["Quality"], y_pred_class))
recall.append(recall_score(df_test_logit["Quality"], y_pred_class))
F1.append(f1_score(df_test_logit["Quality"], y_pred_class))

In [189]:
accuracy_test

[0.9317269076305221,
 0.9196787148594378,
 0.8995983935742972,
 0.9116465863453815,
 0.751004016064257,
 0.8594377510040161]

In [190]:
precision

[0.6818181818181818,
 0.5862068965517241,
 0.5,
 0.5348837209302325,
 0.02564102564102564,
 0.391304347826087]

In [191]:
recall

[0.6, 0.68, 0.88, 0.92, 0.04, 0.72]

In [192]:
F1

[0.6382978723404256,
 0.6296296296296295,
 0.6376811594202899,
 0.6764705882352942,
 0.03125,
 0.5070422535211268]

In [193]:
final_model=pd.DataFrame({'accuracy':accuracy_test,'precision':precision,'recall':recall,'F1':F1},index=['XGB','GB','RF','DT','SVM','Logistic'])

In [194]:
final_model.T


XGB        GB        RF        DT       SVM  Logistic
accuracy   0.931727  0.919679  0.899598  0.911647  0.751004  0.859438
precision  0.681818  0.586207  0.500000  0.534884  0.025641  0.391304
recall     0.600000  0.680000  0.880000  0.920000  0.040000  0.720000
F1         0.638298  0.629630  0.637681  0.676471  0.031250  0.507042